# Generated by Django 3.0.1 on 2019-12-22 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loot',
            old_name='value',
            new_name='percentage',
        ),
    ]
