# Generated by Django 3.0.1 on 2019-12-24 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loot', '0002_auto_20191222_1555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loot',
            old_name='percentage',
            new_name='gp',
        ),
        migrations.RemoveField(
            model_name='loot',
            name='cost',
        ),
    ]
