# Generated by Django 3.0.1 on 2019-12-24 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loot', '0003_auto_20191224_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='loot',
            name='prince_percentage',
            field=models.FloatField(default=100, null=True),
        ),
    ]
