# Generated by Django 3.0.1 on 2019-12-26 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_auto_20191224_2327'),
        ('loot', '0005_auto_20191224_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='loot',
            name='item_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='items.ItemInfo'),
        ),
    ]
