# Generated by Django 3.0.1 on 2019-12-26 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loot', '0006_loot_item_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loot',
            name='gp',
        ),
    ]
