# Generated by Django 3.0.1 on 2019-12-28 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loot', '0008_auto_20191228_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='loot',
            name='comment',
            field=models.CharField(default='', max_length=256),
        ),
    ]
