# Generated by Django 3.0.1 on 2020-01-01 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loot', '0011_loot_character'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loot',
            name='member',
        ),
    ]
