# Generated by Django 3.0.1 on 2020-03-13 22:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('raid', '0029_auto_20200119_1124'),
        ('members', '0029_remove_eplog_affected_characters'),
        ('items', '0010_remove_item_gp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.IntegerField(choices=[(0, 'New Member'), (1, 'Give Item'), (2, 'Give Ep'), (3, 'Create Raid'), (4, 'End Raid'), (5, 'Add To Raid'), (6, 'Remove From Raid'), (7, 'Decay')])),
                ('value', models.CharField(max_length=128)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item', to='items.Item')),
                ('raid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raid', to='raid.Raid')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='target', to='members.Member')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='writer', to='members.Member')),
            ],
        ),
    ]
