# Generated by Django 3.0.1 on 2020-03-13 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raid', '0029_auto_20200119_1124'),
        ('items', '0010_remove_item_gp'),
        ('officers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='item', to='items.Item'),
        ),
        migrations.AlterField(
            model_name='log',
            name='raid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='raid', to='raid.Raid'),
        ),
    ]
