# Generated by Django 3.0.1 on 2020-03-13 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0030_auto_20200313_2354'),
        ('officers', '0004_auto_20200313_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='target_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='target_member', to='members.Member'),
        ),
        migrations.AlterField(
            model_name='log',
            name='action',
            field=models.IntegerField(choices=[(0, 'New Member'), (1, 'Give Loot'), (2, 'Give Ep'), (3, 'Create Raid'), (4, 'End Raid'), (5, 'Add To Raid'), (6, 'Remove From Raid'), (7, 'Decay'), (8, 'Unlock Raid'), (9, 'Delete Loot')]),
        ),
        migrations.AlterField(
            model_name='log',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='target', to='members.Character'),
        ),
    ]
