# Generated by Django 3.0.1 on 2020-04-02 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0005_auto_20200313_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='action',
            field=models.IntegerField(choices=[(0, 'New Member'), (1, 'Give Loot'), (2, 'Give Ep'), (3, 'Create Raid'), (4, 'End Raid'), (5, 'Add To Raid'), (6, 'Remove From Raid'), (7, 'Decay'), (8, 'Unlock Raid'), (9, 'Delete Loot'), (10, 'Bench'), (11, 'Unbench')]),
        ),
    ]
