# Generated by Django 3.0.1 on 2020-03-13 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dungeons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dungeon',
            name='gp_modifier',
            field=models.FloatField(default=1),
        ),
    ]
