# Generated by Django 3.0.1 on 2020-04-02 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dungeons', '0002_dungeon_gp_modifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='dungeon',
            name='ep_worth',
            field=models.FloatField(default=100),
        ),
    ]
