# Generated by Django 3.0.1 on 2019-12-21 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dungeon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('quality', models.IntegerField(choices=[(0, 'Poor'), (1, 'Common'), (2, 'Uncommon'), (3, 'Rare'), (4, 'Epic'), (5, 'Legendary')])),
                ('ep', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Raid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(auto_now_add=True)),
                ('end', models.DateTimeField(default=None)),
                ('dungeon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='raid.Dungeon')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='raid.Member')),
            ],
        ),
        migrations.CreateModel(
            name='RaidMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('start', models.DateTimeField(auto_now_add=True)),
                ('end', models.DateTimeField(default=None)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='raid.Member')),
                ('raid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='raid.Raid')),
            ],
        ),
        migrations.CreateModel(
            name='Loot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('cost', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('given_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='raid.Item')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='raid.Member')),
                ('raid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='raid.Raid')),
            ],
        ),
        migrations.CreateModel(
            name='BenchedRaidMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('ticks', models.IntegerField()),
                ('start', models.DateTimeField(auto_now_add=True)),
                ('end', models.DateTimeField(default=None)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='raid.Member')),
                ('raid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='raid.Raid')),
            ],
        ),
    ]
