# Generated by Django 3.0.1 on 2019-12-22 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_rank'),
        ('dungeons', '0001_initial'),
        ('raid', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loot',
            name='given_by',
        ),
        migrations.RemoveField(
            model_name='loot',
            name='item',
        ),
        migrations.RemoveField(
            model_name='loot',
            name='member',
        ),
        migrations.RemoveField(
            model_name='loot',
            name='raid',
        ),
        migrations.AlterField(
            model_name='benchedraidmember',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='benchedraidmember',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='members.Member'),
        ),
        migrations.AlterField(
            model_name='raid',
            name='dungeon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dungeons.Dungeon'),
        ),
        migrations.AlterField(
            model_name='raid',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='raid',
            name='leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='members.Member'),
        ),
        migrations.AlterField(
            model_name='raidmember',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='raidmember',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='members.Member'),
        ),
        migrations.DeleteModel(
            name='Dungeon',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Loot',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
