# Generated by Django 3.0.1 on 2019-12-21 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='wow_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='member',
            name='discord_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='member',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
