# Generated by Django 3.0.1 on 2019-12-22 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raid', '0002_auto_20191222_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='raid',
            name='state',
            field=models.IntegerField(choices=[(0, 'In Progress'), (1, 'Paused'), (2, 'Failed'), (3, 'Success')], default=0),
        ),
    ]
