# Generated by Django 3.0.1 on 2019-12-26 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raid', '0003_raid_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='raid',
            name='members',
            field=models.ManyToManyField(null=True, to='raid.Raid'),
        ),
    ]
