# Generated by Django 3.0.1 on 2019-12-26 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raid', '0004_raid_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raid',
            name='members',
        ),
    ]
