# Generated by Django 3.0.1 on 2019-12-26 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raid', '0007_auto_20191226_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raid',
            name='raid_members',
            field=models.ManyToManyField(related_name='raid_members', to='raid.RaidMember'),
        ),
    ]
