# Generated by Django 3.0.1 on 2019-12-26 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raid', '0008_auto_20191226_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raidmember',
            name='raid',
        ),
    ]
