# Generated by Django 3.0.1 on 2019-12-27 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raid', '0010_remove_raidmember_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='raidmember',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='raid',
            name='raid_members',
            field=models.ManyToManyField(related_name='raid', to='raid.RaidMember'),
        ),
    ]
