# Generated by Django 3.0.1 on 2019-12-28 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raid', '0011_auto_20191227_0239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='benchedraidmember',
            name='name',
        ),
        migrations.AddField(
            model_name='raid',
            name='benched_raid_members',
            field=models.ManyToManyField(related_name='braid', to='raid.BenchedRaidMember'),
        ),
        migrations.AlterField(
            model_name='benchedraidmember',
            name='ticks',
            field=models.IntegerField(default=0),
        ),
    ]
