# Generated by Django 3.0.1 on 2019-12-30 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0021_remove_member_member_class'),
        ('raid', '0018_auto_20191230_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='benchedraidmember',
            name='member',
        ),
        migrations.AddField(
            model_name='benchedraidmember',
            name='character',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='members.Character'),
        ),
    ]
