# Generated by Django 3.0.1 on 2019-12-30 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raid', '0019_auto_20191230_1146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='raid',
            old_name='raid_members',
            new_name='raid_characters',
        ),
    ]
