# Generated by Django 3.0.1 on 2020-01-02 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raid', '0023_auto_20191230_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raid',
            name='benched_raid_characters',
        ),
        migrations.RemoveField(
            model_name='raid',
            name='raid_characters',
        ),
        migrations.AddField(
            model_name='benchedraidcharacter',
            name='raid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='raid.Raid'),
        ),
        migrations.AddField(
            model_name='raidcharacter',
            name='raid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='raid.Raid'),
        ),
    ]
