# Generated by Django 3.0.1 on 2020-01-02 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0023_auto_20191230_1901'),
        ('raid', '0024_auto_20200102_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benchedraidcharacter',
            name='character',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='members.Character'),
        ),
        migrations.AlterField(
            model_name='benchedraidcharacter',
            name='raid',
            field=models.ForeignKey(default=319, on_delete=django.db.models.deletion.CASCADE, related_name='benchedraidcharacter', to='raid.Raid'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='raidcharacter',
            name='character',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='members.Character'),
        ),
        migrations.AlterField(
            model_name='raidcharacter',
            name='raid',
            field=models.ForeignKey(default=319, on_delete=django.db.models.deletion.CASCADE, related_name='raidcharacter', to='raid.Raid'),
            preserve_default=False,
        ),
    ]
