# Generated by Django 3.0.1 on 2020-01-05 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raid', '0026_auto_20200105_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='benchedraidcharacter',
            name='tmp_ep',
        ),
    ]
