# Generated by Django 3.0.1 on 2020-01-19 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raid', '0028_auto_20200105_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raid',
            name='state',
            field=models.IntegerField(choices=[(0, 'In Progress'), (1, 'Paused'), (2, 'Failed'), (3, 'Success'), (4, 'Editing')], default=0),
        ),
    ]
