# Generated by Django 3.0.1 on 2020-04-02 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raid', '0029_auto_20200119_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raid',
            name='state',
            field=models.IntegerField(choices=[(0, 'In Progress'), (1, 'Paused'), (2, 'Failed'), (3, 'Success'), (4, 'Editing'), (5, 'Ready')], default=5),
        ),
    ]
