# Generated by Django 3.0.1 on 2019-12-21 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wow_id', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=128)),
                ('quality', models.IntegerField(choices=[(0, 'Poor'), (1, 'Common'), (2, 'Uncommon'), (3, 'Rare'), (4, 'Epic'), (5, 'Legendary')])),
                ('ep', models.IntegerField()),
            ],
        ),
    ]
