# Generated by Django 3.0.1 on 2019-12-22 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20191222_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='ep',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
