# Generated by Django 3.0.1 on 2019-12-23 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20191222_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='quality',
            field=models.IntegerField(choices=[(0, 'Poor'), (1, 'Common'), (2, 'Uncommon'), (3, 'Rare'), (4, 'Epic'), (5, 'Legendary'), (6, 'Artifact')], null=True),
        ),
    ]
