# Generated by Django 3.0.1 on 2019-12-23 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_auto_20191223_2148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='quality',
            new_name='item_quality',
        ),
        migrations.AddField(
            model_name='item',
            name='item_class',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='item',
            name='item_level',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='item_subclass',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='item',
            name='item_type',
            field=models.IntegerField(choices=[(0, 'Weaponmainhand'), (1, 'Twohweapon'), (2, 'Body'), (3, 'Legs'), (4, 'Feet'), (5, 'Robe'), (6, 'Chest'), (7, 'Non Equip'), (8, 'Shield'), (9, 'Hand'), (10, 'Wrist'), (11, 'Weapon'), (12, 'Trinket'), (13, 'Tabard'), (14, 'Bag'), (15, 'Waist'), (16, 'Finger'), (17, 'Shoulder'), (18, 'Weaponoffhand'), (19, 'Holdable'), (20, 'Head'), (21, 'Cloak'), (22, 'Neck'), (23, 'Rangedright'), (24, 'Ranged'), (25, 'Ammo'), (26, 'Thrown'), (27, 'Relic')], null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='item_type_name',
            field=models.CharField(default='', max_length=256),
        ),
    ]
