# Generated by Django 3.0.1 on 2019-12-24 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_auto_20191224_2317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iteminfo',
            old_name='slot',
            new_name='name',
        ),
    ]
