# Generated by Django 3.0.1 on 2019-12-26 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_auto_20191224_2327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='gp',
        ),
    ]
