# Generated by Django 3.0.1 on 2019-12-21 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_id', models.BigIntegerField(null=True)),
                ('name', models.CharField(max_length=50)),
                ('joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
