# Generated by Django 3.0.1 on 2019-12-24 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_auto_20191222_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='member_class',
            field=models.IntegerField(choices=[(0, 'Druid'), (1, 'Hunter'), (2, 'Mage'), (3, 'Priest'), (4, 'Rogue'), (5, 'Shaman'), (6, 'Warlock'), (7, 'Warrior')], null=True),
        ),
    ]
