# Generated by Django 3.0.1 on 2019-12-24 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_member_member_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='joined',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
