# Generated by Django 3.0.1 on 2019-12-24 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_auto_20191224_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='rank',
            field=models.IntegerField(choices=[(0, 'Member'), (10, 'Raid Leader'), (100, 'Officer'), (1000, 'Admin')], default=0, null=True),
        ),
    ]
