# Generated by Django 3.0.1 on 2019-12-24 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_auto_20191224_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='ep',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='gp',
            field=models.FloatField(null=True),
        ),
    ]
