# Generated by Django 3.0.1 on 2019-12-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_auto_20191226_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='ep',
            field=models.IntegerField(default=0),
        ),
    ]
