# Generated by Django 3.0.1 on 2019-12-27 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_member_ep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='rank',
            field=models.IntegerField(choices=[(0, 'Member'), (5, 'Raider'), (10, 'Raid Leader'), (100, 'Officer'), (1000, 'Admin')], default=0, null=True),
        ),
    ]
