# Generated by Django 3.0.1 on 2019-12-28 18:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_auto_20191227_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
