# Generated by Django 3.0.1 on 2019-12-29 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_auto_20191228_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='gp',
            field=models.IntegerField(default=0),
        ),
    ]
