# Generated by Django 3.0.1 on 2019-12-29 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0018_auto_20191229_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decay',
            name='member',
        ),
        migrations.AddField(
            model_name='decay',
            name='affected_members',
            field=models.ManyToManyField(related_name='decays', to='members.Member'),
        ),
    ]
