# Generated by Django 3.0.1 on 2019-12-29 22:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0019_auto_20191229_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='character',
            name='member_class',
            field=models.IntegerField(choices=[(0, 'Druid'), (1, 'Hunter'), (2, 'Mage'), (3, 'Priest'), (4, 'Rogue'), (5, 'Shaman'), (6, 'Warlock'), (7, 'Warrior')], null=True),
        ),
    ]
