# Generated by Django 3.0.1 on 2019-12-30 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0020_auto_20191229_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='member_class',
        ),
    ]
