# Generated by Django 3.0.1 on 2019-12-30 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0021_remove_member_member_class'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='member_class',
            new_name='character_class',
        ),
    ]
