# Generated by Django 3.0.1 on 2019-12-30 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0022_auto_20191230_1156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='member',
            new_name='owner',
        ),
    ]
