# Generated by Django 3.0.1 on 2020-01-03 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0025_auto_20200103_0008'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Decay',
            new_name='DecayLog',
        ),
    ]
