# Generated by Django 3.0.1 on 2020-01-03 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0026_auto_20200103_0009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decaylog',
            name='affected_members',
        ),
        migrations.RemoveField(
            model_name='eplog',
            name='affected_members',
        ),
        migrations.AddField(
            model_name='decaylog',
            name='affected_characters',
            field=models.ManyToManyField(related_name='decays', to='members.Character'),
        ),
        migrations.AddField(
            model_name='eplog',
            name='affected_characters',
            field=models.ManyToManyField(related_name='eplog', to='members.Character'),
        ),
    ]
