# Generated by Django 3.0.1 on 2020-01-05 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0028_auto_20200103_0022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eplog',
            name='affected_characters',
        ),
    ]
