# Generated by Django 3.0.1 on 2020-03-13 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0029_remove_eplog_affected_characters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eplog',
            name='raid',
        ),
        migrations.DeleteModel(
            name='DecayLog',
        ),
        migrations.DeleteModel(
            name='EPLog',
        ),
    ]
