# Generated by Django 3.0.1 on 2020-03-27 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0030_auto_20200313_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='rank',
            field=models.IntegerField(choices=[(0, 'Member'), (5, 'Raider'), (10, 'Raid Leader'), (100, 'Officer'), (1000, 'Guild Master')], default=0, null=True),
        ),
    ]
