# Generated by Django 3.0.1 on 2020-03-29 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0031_auto_20200327_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='ep',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='member',
            name='gp',
            field=models.FloatField(default=0),
        ),
    ]
